/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author yarel
 */
public class AgregarEntrenador extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public AgregarEntrenador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFIdEntrenador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        txtFPreEvolucion = new javax.swing.JTextField();
        txtFEvolucion = new javax.swing.JTextField();
        txtFAltura = new javax.swing.JTextField();
        txtFPeso = new javax.swing.JTextField();
        txtFPs = new javax.swing.JTextField();
        txtFIdEntrenador1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFIdEntrenador.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFIdEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFIdEntrenadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtFIdEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("idEntrenador:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellido Paterno:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Ciudad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Telefono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("idEstado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtFNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, 30));

        txtFPreEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPreEvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPreEvolucionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFPreEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 30));

        txtFEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFEvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFEvolucionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 30));

        txtFAltura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAlturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 30));

        txtFPeso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPesoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, 30));

        txtFPs.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPsActionPerformed(evt);
            }
        });
        getContentPane().add(txtFPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, 30));

        txtFIdEntrenador1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFIdEntrenador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFIdEntrenador1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtFIdEntrenador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Apellido Materno:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 330));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonAgregar.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 50));

        btnAgregar.setBackground(java.awt.Color.orange);
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(102, 62, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        btnMenu.setBackground(java.awt.Color.orange);
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(102, 62, 0));
        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btnRegresar.setBackground(java.awt.Color.orange);
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 62, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonRegresar.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/47cb64380cd79123087f92f0a6345982b3b78066_gif_63b0ca0946bb3c10566e36dd0d17e3e1.gif.a78457bd7e228a7e2e143c513472d41e (1).gif"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 340, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/16AgregarEntrenador.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFIdEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFIdEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIdEntrenadorActionPerformed

    private void txtFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNombreActionPerformed

    private void txtFPreEvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPreEvolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPreEvolucionActionPerformed

    private void txtFEvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFEvolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFEvolucionActionPerformed

    private void txtFAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAlturaActionPerformed

    private void txtFPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPesoActionPerformed

    private void txtFPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPsActionPerformed

    private void txtFIdEntrenador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFIdEntrenador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIdEntrenador1ActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        ActualizarEntrenador actEnt= new ActualizarEntrenador();
        actEnt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal= new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEntrenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFAltura;
    private javax.swing.JTextField txtFEvolucion;
    private javax.swing.JTextField txtFIdEntrenador;
    private javax.swing.JTextField txtFIdEntrenador1;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFPeso;
    private javax.swing.JTextField txtFPreEvolucion;
    private javax.swing.JTextField txtFPs;
    // End of variables declaration//GEN-END:variables
}
